// let x = 'y'
// let y = 'z'
// let z = 'x'

// let data = !(x === 'y' || y === 'y' || z === 'y')
// console.log(data)

// var dataString = "DR AGUSTINUS B, SP.OT/DR RACHIM,SP.JP/DR FREDDY,SP.PD/DR MAR";
// var keyword = "AGUSTINUS";

// // Metode indexOf
// if (dataString.indexOf(keyword) !== -1) {
//     console.log("Kata ditemukan!");
// } else {
//     console.log("Kata tidak ditemukan.");
// }

// // Metode includes
// if (dataString.includes(keyword)) {
//     console.log("Kata ditemukan!");
// } else {
//     console.log("Kata tidak ditemukan.");
// }
// ARI PRABOWO(IGD)
// DR AGUSTINUS B, SP.OT/DR ALFONS,SP.AN/DR RACHIM,SP.JP/DR RAH
// DR AGUSTINUS B, SP.OT/DR ALFONS,SP.AN/DR RAHMAD,SP.PD/DR U Y
// DR AGUSTINUS B, SP.OT/DR RACHIM,SP.JP/DR FREDDY,SP.PD/DR MAR
// DR AGUSTINUS B, SP.OT/DR RADHITIO,SP.A/DR SONNY,SP.BS/DR ALF
// DR AGUSTINUS, SP.OT/DR SONNY,SP.AN/DR MARKUS, SP.AN/DR ALFON
// DR AGUSTINUS,SP.OT/DR ALFONS,SP.AN/DR RACHIM,SP.JP/DR FREDDY
// DR ARI, SP.P/ DR BORIS, SP.B (PARU)
// DR ARI,SP.P (PD)
// DR ARI,SP.P/DR AGUSTINUS,SP.OT (PARU)
// DR ARI,SP.P/DR BORIS, SP.B/DR RAHMAD,SP.PD/DR ALFONS, SP.AN
// DR ARI,SP.P/DR MARKUS,SP.AN/DR BORIS,SP.B (PARU)
// DR ARI,SP.P/DR MARKUS,SP.AN/DR RACHIM,SP.JP (PARU-ICU)
// DR BORIS, SP.B/DR ALFONS,SP.AN/DR FREDDY,SP.PD (ICU,BEDAH)
// DR BORIS, SP.B/DR FREDDY,SP.PD/DR ALFONS,SP.AN(BEDAH)
// DR BORIS, SP.B/DR HARTONO,SP.PD/DR ALFONS,SP.AN (PD) PD
// DR BORIS,SP.B/DR AGUSTINUS B,SP.OT/DR ALFONS,SP.AN.DR MARKUS
// DR BORIS,SP.B/DR ALFONS,SP.AN/DR HERISA,SP.MK/DR MARKUS,SP.A
// DR BORIS,SP.B/DR ALFONS,SP.AN/DR MARKUS,SP.AN/DR FREDDY,SP.P
// DR BORIS,SP.B/DR MARKUS,SP.AN/DR ALFONS,SP.AN/DR RAHMAD,SP.P
// DR BORIS,SP.B/DR RADHITIO,SP.A/DR ALFONS,SP.AN (VIP)
// DR DAVIS, SP.OG /DR MARKUS ,SP.AN (NIFAS)
// DR DAVIS,SP.OG/DR MARKUS,SP.AN/DR ALFONS,SP.AN (NIFAS)
// DR DAVIS,SP.OG/DR RAHMAD,SP.PD/DR ALFONS,SP.AN (VK,ICU,NIFAS
// DR DIANA, SP.A (ANAK,VIP)
// DR DIANA, SP.A/DR MARKUS,SP.AN/DR HERISA,SP.MK/DR RHADITIO,S
// DR DIANA,SP.A/DR  YUNITA, SP.THT (ANAK)
// DR DIANA,SP.A/DR RADHITIO, SP.A (VIP)
// DR DIANA,SP.A/DR RADHITIO,SP.A (ANAK)
// DR DIANA,SP.A/DR RADHITIO,SP.A (PERINATOLOGI)
// DR DIANA,SP.A/DR SONNY,SP.BS/DR ALFONS,SP.AN/DR MARKUS,SP.AN
// DR FENNY,SP.KJ (1B)
// DR FREDDY, SP.PD(IGD)
// DR FREDDY,SP.PD/DR ALFONS,SP.AN/DR MARKUS,SP.AN (IGD-ICU)
// DR FREDDY,SP.PD/DR HANARTOAJI,SP.PD/DR TOGU,SP.KFR (PD)
// DR FREDDY,SP.PD/DR HANARTOAJI,SP.S/DR TOGU,SP.KFR (PD)
// DR FREDDY,SP.PD/DR MARKUS,SP.AN/DR ARI,SP.P/DR U YESSIKA, SP
// DR FREDDY,SP.PD/DR MARKUS,SP.AN/DR MUDIB,SP.AN/DR HERISA,SP.
// DR FREDDY,SP.PD/DR SONNY, SP.BS (PD)
// DR HANARTOAJI, SP.S (IGD)
// DR HANARTOAJI,SP.S/DR MARKUS,SP.AN (IGD-ICU)
// DR HERLING,SP.OG/DR HARTONO,SP.PD (NIFAS)
// DR HERLING,SP.OG/DR RAHMAD,SP.PD/DR MARKUS,SP.AN  (NIFAS)
// DR MARSITA LITA, SP.M(1B)
// DR MARSITA LITA, SP.M/DR FREDDY,SP.PD/DR FENNY,SP.KJ (PD)
// DR MUDIB, SP.B (BEDAH)
// DR MUDIB, SP.B/DR ALFONS, SP.AN/DR HARTONO, SP.PD(BEDAH)
// DR MUDIB, SP.B/DR HARTONO, SP.PD/DR MARKUS, SP.AN (BEDAH)
// DR MUDIB,SP.B/DR ALFONS,SP.AN/DR FREDDY, SP.PD (1C-BEDAH)
// DR MUDIB,SP.B/DR ALFONS,SP.AN/DR MARKUS, AP.AN (ICU)
// DR MUDIB,SP.B/DR ALFONS,SP.AN/DR MARKUS,SP.AN(BEDAH)
// DR MUDIB,SP.B/DR ALFONS,SP.AN/DR MARKUS,SP.AN/DR RAHMAD,SP.P
// DR MUDIB,SP.B/DR HARTONO,SP.PD (1C)
// DR MUDIB,SP.B/DR MARKUS, SP.AN/DR RAHMAD, SP.PD (BEDAH)
// DR MUDIB,SP.B/DR MARKUS, SP.AN/DR RAHMAD, SP.PD(BEDAH)
// DR MUDIB,SP.B/DR RAHMAD,SP.PD/DR TOGU,SP.KFR/DR ALFONS,SP.AN
// DR MUSLIM,SP.THT/DR DJOKO S TARDAN,SP.M/DR ALFONS,SP.AN/DR S
// DR MUSLIM,SP.THT/DR MARKUS,SP.AN/DR ALFONS,SP.AN/DR FENNY,SP
// DR NOVI SALITA , SP.OG/DR ALFONS,SP.AN/DR RACHIM,SP.JP (NIFA
// DR RACHIM, SP.JP/ HARTONO, SP.PD (PD)
// DR RACHIM, SP.JP/DR ARI, SP.P -1B
// DR RACHIM, SP.JP/DR FREDDY, SP.PD (PD)
// DR RACHIM,SP.JP/DR ARI,SP.P/DR ALFONS, SP.AN (PD-ICU)
// DR RACHIM,SP.JP/DR HANARTOAJI,SP.S/DR RAHMAD,SP.PD (1B)
// DR RACHIM,SP.JP/DR RAHMAD,SP.PD/DR MARKUS, SP.AN (ICU-PD)
// DR RACHIM,SP.JP/DR TEGUH,SP.KK/DR ARI,SP.P (1B-ICU-VIP)
// DR RADHITIO ADI, SP.A (VIP)
// DR RADHITIO ADI,SP.A (ANAK)
// DR RAHMAD, SP.PD/DR FENNY, SP.KJ (1B)
// DR RAHMAD, SP.PD/DR FENNY, SP.KJ (PD)
// DR RAHMAD,SP.PD/DR U YESSIKA, SP.B (PD)
// DR RAHMAD,SP.PD/DR VIVI,SP.N/DR ALFONS,SP.AN (SYARAF-ICU)
// DR RAHMAD,SP.PD/FENNY,SP.KJ/DR TOGU, SP.KFR/DR HANARTOAJI, S
// DR SONNY, SP.BS(NEURO)
// DR SONNY,SP.BS/ DR RAHMAD,SP.PD/ DR TOGU,SP.KFR/ DR MARKUS,
// DR SONNY,SP.BS/DR AGUSTINUS, SP.OT/DR ALFONS,SP.AN (SARAF)
// DR SONNY,SP.BS/DR MARKUS,SP.AN/DR HARTONO,SP.PD/DR HANARTOAJ
// DR SONNY,SP.BS/DR MUDIB,SP.B/DR VIVI,SP.N/DR RAHMAD,SP.PD/DR
// DR SONNY,SP.BS/DR NOVI SALITA, SP.OG (SARAF)
// DR STEVIE, SP.A/DR  ALFONS, SP.AN (ANAK)
// dr u yessika,sp.b/dr alfons,sp.an/dr hartono,sp.pd/dr markus
// DR U YESSIKA,SP.B/DR ALFONS,SP.AN/DR RAHMAD,SP.PD (1C)
// DR U YESSIKA,SP.B/DR FREDDY, SP.PD/DR  MARKUS, SP.AN (BEDAH)
// DR U.YESSIKA, SP.B (BEDAH)
// DR U.YESSIKA,SP.B/DR ALFONS, SP.AN (BEDAH)
// DR VIVI, SP.N/DR FENNY,SP.KJ/DR ARI,SP.P/DR TOGU ,SP.KFR (SY
// dr vivi, sp.n/dr teguh,sp.kk/dr togu,sp.kfr (neuro)
// DR VIVI,SP.N/DR FREDDY,SP.PD/DR TEGUH,SP.KK/DR ARI,SP.P (NEU
// DR VIVI,SP.N/DR RACHIM,SP.JP/DR ARI,SP.P (NEURO)
// DR YUNITA,SP,THT/DR MARKUS,SP.AN/DR HARTONO,SP.PD (IGD-ICU)
// DR YUNITA,SP.THT/DR ALFONS,SP.AN/DRG UNDARI (BEDAH)
// DR ZAINUL, SP.B/ DR RAHMAD, SP.PD (BEDAH)
// DR ZAINUL, SP.B/DR ALFONS, SP.AN (1B)
// DR ZAINUL, SP.B/DR HARTONO,SP.PD (BEDAH)
// DR ZAINUL,SP.B/DR ALFONS,SP.AN/DR RAHMAD,SP.PD/DR ARI,SP.P (
// DR ZAINUL,SP.B/DR FREDDY,SP.PD/DR MARKUS,SP.AN/DR ARI,SP.P (
// DR ZAINUL,SP.B/DR RAHMAD,SP.PD/DR RACHIM,SP.JP/DR ALFONS,SP.
// DR. AGUSTINUS B P SP.OT/DR. MARKUS SP.AN (1B)
// DR. AGUSTINUS B SP.OT (BEDAH)
// DR. AGUSTINUS B SP.OT (IGD)
// DR. AGUSTINUS B SP.OT/DR. ALFONS SP.AN (1C)
// DR. AGUSTINUS B SP.OT/DR. ALFONS SP.AN (ANAK)
// DR. AGUSTINUS B SP.OT/DR. ALFONS SP.AN (BEDAH)
// DR. AGUSTINUS B SP.OT/DR. ARI SP.P (1B)
// DR. AGUSTINUS B SP.OT/DR. ARI SP.P/DR. MARKUS SP.AN (1B)
// DR. AGUSTINUS B SP.OT/DR. HARTONO SP.PD/DR. MARKUS SP.AN (1C
// DR. AGUSTINUS B SP.OT/DR. MARKUS SP.AN (1C)
// DR. AGUSTINUS B SP.OT/DR. MARKUS SP.AN (BEDAH)
// DR. AGUSTINUS B SP.OT/DR. MARKUS SP.AN (VIP)
// DR. AGUSTINUS B SP.OT/DR. MARKUS SP.AN/DR. HARTONO SP.PD/DR.
// DR. AGUSTINUS B SP.OT/DR. MARKUS SP.AN/DR. RAHMAD SP.PD/DR.
// DR. AGUSTINUS B SP.OT/DR. RAHMAD SP.PD/DR. MARKUS SP.AN (BED
// DR. AGUSTINUS B SP.OT/DR. RAHMAD/DR. ALFONS (1C)
// DR. AGUSTINUS B SP.OT/DR. RAHMAD/DR. ALFONS (BEDAH)
// DR. AGUSTINUS B SP.OT/DR. RAHMAD/DR. ALFONS (VIP)
// DR. AGUSTINUS B SP.OT/DR. SONNY SP.BS/DR. HARTONO SP.PD/DR.
// DR. AGUSTINUS B SP.OT/DR.HARTONO/DR. MARKUS (BEDAH)
// DR. AGUSTINUS B, SP.OT / DR. ALFONS, SP.AN ( PD )
// DR. AGUSTINUS B, SP.OT / DR. MARKUS, SP.AN / DR. ALFONS, SP.
// DR. AGUSTINUS BUDHI, SP.OT / DR. MARKUS, SP.AN ( BDH )
// DR. AGUSTINUS SP.OT/DR.MARKUS/DR. ALFONS (BEDAH)
// DR. AGUSTINUS, SP.OT / DR. ARI, SP.P / DR. HARTONO, SP.PD /
// DR. AGUSTINUS, SP.OT / DR. MARKUS, SP.AN / DR. ALFONS, SP.AN
// DR. AGUSTINUS, SP.OT / DR. MARKUS, SP.AN / DR. RAHMAD, SP.PD
// DR. AGUSTINUS,SP.OT/DR.ALFONS(BDH)
// DR. ARI P, SP.P / DR. RACHIM, SP.JP ( PARU )
// DR. ARI P,SP.P (PARU)
// DR. ARI PRABOWO, SP. P ( PARU )
// DR. ARI PRABOWO, SP. P (1B)
// DR. ARI PRABOWO, SP.P ( IGD,1B )
// DR. ARI PRABOWO, SP.P ( IGD,PARU )
// DR. ARI PRABOWO, SP.P / DR. MARKUS, SP.AN ( ICU,PARU )
// DR. ARI SP.P/DR. BORIS SP.B (PARU)
// DR. ARI SP.P/DR. HANARTOAJI SP.S (PARU)
// DR. ARI SP.P/DR. M. NUR RACHIM SP.JP (PD)
// DR. ARI SP.P/DR. RACHIM SP.JP (PD,VIP)
// DR. ARI SP.P/DR. URAY YESSIKA SP.B (1C)
// DR. ARI SP.P/DR. URAY YESSIKA SP.B (PARU)
// DR. ARI, SP.P ( ISO PARU )
// DR. ARI, SP.P / DR. ESTU, SP.N / DR. TOGU, SP.KFR / DR. RACH
// DR. ARI, SP.P / DR. FREDDY, SP.PD / DR. RACHIM, SP.JP ( PARU
// DR. ARI, SP.P / DR. RAHMAD, SP.PD ( ISO PARU )
// DR. ARI, SP.P / DR. TOGU, SP.KFR ( PD )
// DR. BORIS SP.B (IGD)
// DR. BORIS SP.B/DR. ALFONS SP.AN (BEDAH)
// DR. BORIS SP.B/DR. ALFONS SP.AN/DR. RAHMAD SP.PD (BEDAH)
// DR. BORIS SP.B/DR. FREDDY SP.AN (BEDAH)
// DR. BORIS SP.B/DR. MARKUS SP.AN (BEDAH)
// DR. BORIS SP.B/DR. MARKUS SP.AN/DR. ARI SP.P/DR. RAHMAD SP.P
// DR. BORIS SP.B/DR. RACHIM SP.JP/DR. FREDDY SP.PD/DR. ALFONS
// DR. BORIS SP.B/DR. RAHMAD SP.PD/DR. MARKUS SP.AN (BEDAH)
// DR. BORIS SP.B/DR. STEVIE SP.A (BEDAH)
// DR. BORIS SP.B/DR.ALFONS SP.AN (BEDAH)
// DR. BORIS SP.P/DR. MARKUS SP.AN (1C)
// DR. BORIS, SP.B ( 1C )
// DR. BORIS, SP.B ( BEDAH )
// DR. BORIS, SP.B / DR. ALFONS, SP.AN ( 1C )
// DR. BORIS, SP.B / DR. ALFONS, SP.AN / DR. HARTONO, SP.PD / D
// DR. BORIS, SP.B / DR. MARKUS, SP.AN / DR. ARI, SP.P / DR. RA
// DR. BORIS, SP.B / DR. MARKUS, SP.AN / DR. HARTONO, SP.PD / D
// DR. BORIS, SP.B / DR. RAHMAD, SP.PD / DR. MARKUS, SP.AN ( 1C
// DR. DAVIS SP.OG (NIFAS,VK)
// DR. DAVIS SP.OG (NIFAS)
// DR. DAVIS SP.OG (VK,NFS)
// DR. DAVIS SP.OG (VK)
// DR. DAVIS SP.OG/DR. ALFONS SP.AN (NIFAS)
// DR. DAVIS SP.OG/DR. ALFONS SP.AN (VK,NIFAS)
// DR. DAVIS SP.OG/DR. ARI SP.P/DR. BORIS SP.B/DR. MARKUS SP.AN
// DR. DAVIS SP.OG/DR. MARKUS SP.AN (NIFAS)
// DR. DAVIS SP.OG/DR. MARKUS SP.AN (VK,NFS)
// DR. DAVIS SP.OG/DR. RAHMAD SP.PD/DR. ALFONS SP.AN (NIFAS)
// DR. DAVIS, SP.OG / DR. MARKUS, SP.AN ( NFS )
// DR. DIANA BANCIN SP.A/DR. RACHIM SP.JP (ANAK)
// DR. DIANA BANCIN, SP.A ( IGD,VIP )
// DR. DIANA BANCIN, SP.A (ANAK / VIP)
// DR. DIANA BANCIN, SP.A (ANAK)
// DR. DIANA BANCIN, SP.A (PERINATOLOGI)
// DR. DIANA SP.A (ANAK,VIP)
// DR. DIANA SP.A/DR. TEGUH SP.KK/DR. RACHIM SP.JP (ANAK)
// DR. DIANA SPA(PERINATOLOGI)
// DR. DIANA, SP.A / DR. RADHITIO, SP.A / DR. ALFONS, SP.AN ( I
// DR. DIANA, SP.A / DR. TOGU, SP.KFR / DR. RADHITIO, SP.A / DR
// DR. DJOKO S TARDAN SP.M/DR. ALFONS SP.AN (BEDAH)
// DR. DJOKO S TARDAN SP.M/DR. MARKUS SP.AN (BEDAH)
// DR. DJOKO S TARDAN, SP.M ( 1C )
// DR. ESTU DEWI MAHANI, SP.N ( 1B )
// DR. ESTU DEWI SP.N (SYARAF)
// DR. ESTU MAHARANI SP.N (SYARAF)
// DR. ESTU SP.N (PD)
// DR. ESTU, SP.N / DR. MARSITA, SP.M ( SYARAF )
// DR. FENNY SP.KJ/DR. HARTONO SP.PD (SYARAF)
// DR. FENNY, SP.KJ / DR. RAHMAD, SP.PD ( PD )
// DR. FREDDY (PD)
// DR. FREDDY PANJAITAN SP.PD (BEDAH)
// DR. FREDDY SP.PD (PD)
// DR. FREDDY SP.PD/DR. ARI SP.P (PD)
// DR. FREDDY SP.PD/DR. FENNY SP.KJ (PD)
// DR. FREDDY SP.PD/DR. HANARTOAJI SP.S (PD)
// DR. FREDDY SP.PD/DR. HANARTOAJI SP.S (VIP,ICU-ICCU,SYARAF)
// DR. FREDDY SP.PD/DR. MARKUS SP.AN (PD)
// DR. FREDDY, SP.PD / DR. ALFONS, SP.AN ( 1B )
// DR. FREDDY, SP.PD / DR. HANARTOAJI, SP.S ( VIP )
// DR. FREDDY, SP.PD / DR. HANARTOAJI, SP.S / DR. FENNY, SP.KJ
// DR. FREEDY SP.B/DR. HANARTOAJI SP.S (1B,ICU-ICCU)
// DR. HANARTO SP.PD/DR. HARTONOAJI SP.S (PD)
// DR. HANARTOAJI A.P, SPS (1B)
// DR. HANARTOAJI A.P, SPS (PD)
// DR. HANARTOAJI A.P, SPS (VIP)
// DR. HANARTOAJI SP.S (SYARAF)
// DR. HANARTOAJI SP.S/DR. ALFONS SP.AN (ICU-ICCU,SYARAF)
// DR. HANARTOAJI SP.S/DR. FENNY SP.KJ (SYARAF)
// DR. HANARTOAJI SP.S/DR. FREDDY SP.PD (SYARAF)
// DR. HANARTOAJI SP.S/DR. FREDDY/DR. TOGU (1B)
// DR. HANARTOAJI SP.S/DR. HARTONO SP.PD (1B)
// DR. HANARTOAJI SP.S/DR. RACHIM SP.JP (SYARAF)
// DR. HANARTOAJI SP.S/DR. RAHMAD  SP.PD (1B,VIP)
// DR. HANARTOAJI SP.S/DR. RAHMAD SP.PD (PD)
// DR. HANARTOAJI SP.S/DR. RAHMAD SP.PD (SYARAF)
// DR. HANARTOAJI SP.S/DR. TOGU SP.KFR (1B)
// DR. HANARTOAJI SP.S/DR.ARI SP.P (SYARAF)
// DR. HANARTOAJI SPS(SARAF)
// DR. HANARTOAJI SPS/DR. ARI SP.P (PARU)
// DR. HANARTOAJI SPS/DR. ARI SPP(SARAF)
// DR. HANARTOAJI SPS/RAHMAD(SARAF)
// DR. HANARTOAJI, SP.S / DR. HARTONO, SP.PD / DR. RACHIM, SP.J
// DR. HANARTOAJI, SP.S / DR. RAHMAD, SP.PD / DR. TOGU, SP.KFR
// DR. HARTONO SP.PD ( 1B )
// DR. HARTONO SP.PD (IGD)
// DR. HARTONO SP.PD (PD)
// DR. HARTONO SP.PD/DR. FENNY SP.KJ/DR.BORIS SP.B (PD)
// DR. HARTONO SP.PD/DR. HANARTOAJI SP.S (PD)
// DR. HARTONO SP.PD/DR. M. NUR RACHIM SP.JP (PD)
// DR. HARTONO SP.PD/DR. MARKUS SP.AN/DR. ALFONS SP.AN (1B)
// DR. HARTONO SP.PD/DR. RACHIM SP.JP/DR. MARSITA LITA SP.M (PD
// DR. HARTONO SP.PD/DR.HANARTOAJI SP.S(1B)
// DR. HARTONO SPPD (1B)
// DR. HARTONO SPPD/DR.HANARTOAJI SPS(PD)
// DR. HARTONO, SP.PD / DR. ALFONS, SP.AN ( 1B )
// DR. HARTONO, SP.PD / DR. ALFONS, SP.AN ( ICU )
// DR. HARTONO, SP.PD / DR. ALFONS, SP.AN ( PD )
// DR. HARTONO, SP.PD / DR. HANARTOAJI, SP.S / DR. MARKUS, SP.A
// DR. HARTONO, SP.PD / DR. MARKUS, SP.AN ( PD )
// DR. HARTONO, SP.PD / DR. RACHIM, SP.JP ( PD )
// DR. HARTONO,SP. PD (1B)
// DR. HERLING FJ, SP.OG (VK,NFS)
// DR. HERLING SP.OG/DR. ALFONS SP.AN (VK,NFS)
// DR. HERLING, SP.OG ( NIFAS )
// DR. HERLING, SP.OG / DR. MARKUS, SP.AN ( NIFAS )
// DR. M NUR RACHIM SP.JP/DR. ALFONS SP.AN (ICU)
// DR. M. NUR RACHIM SP.JP (1B,VIP)
// DR. M. NUR RACHIM SP.JP (ICU,PD)
// DR. M. NUR RACHIM SP.JP (PD)
// DR. M. NUR RACHIM SP.JP (VIP)
// DR. M. NUR RACHIM SP.JP/DR. RAHMAD/DR. FENNY (PD)
// DR. M. NUR RACHIM, SP.JP ( 1B )
// DR. M. NUR RACHIM, SP.JP ( ANAK )
// DR. MARIA ADE SP.M (1C)
// DR. MUDIB SP.B (1B)
// DR. MUDIB SP.B (BEDAH)
// DR. MUDIB SP.B (VIP)
// DR. MUDIB SP.B/DR. ALFONS SP.AN (BEDAH)
// DR. MUDIB SP.B/DR. ALFONS SP.AN/DR. MARKUS SP.AN/DR. ARI SP.
// DR. MUDIB SP.B/DR. FENNY SP.KJ/DR. MARKUS SP.AN (ICU-ICCU,BE
// DR. MUDIB SP.B/DR. FREDDY SP.PD/DR. MARKUS SP.AN (BEDAH)
// DR. MUDIB SP.B/DR. MARKUS SP.AN (BEDAH)
// DR. MUDIB SP.B/DR. MARKUS SP.AN (VIP)
// DR. MUDIB SP.B/DR. MARKUS/DR. ALFONS (BEDAH)
// DR. MUDIB SP.B/DR. RACHIM SP.JP/DR. FREDDY SP.PD (1C)
// DR. MUDIB SP.B/DR. RAHMAD SP.PD (BEDAH)
// DR. MUDIB SP.B/DR. RAHMAD SP.PD/DR. MARKUS SP.AN (BEDAH)
// DR. MUDIB SP.PD (PD)
// DR. MUDIB, SP.B / DR. ALFONS, SP.AN ( 1C )
// DR. MUDIB, SP.B / DR. ALFONS, SP.AN / DR. HARTONO, SP.PD / D
// DR. MUDIB, SP.B / DR. ALFONS, SP.AN / DR. MARKUS, SP.AN ( IG
// DR. MUDIB, SP.B / DR. ARI, SP.P ( BDH,PARU )
// DR. MUDIB, SP.B / DR. MARKUS, SP.AN ( 1B,1C )
// DR. MUDIB, SP.B / DR. MARKUS, SP.AN ( 1C )
// DR. MUDIB, SP.B / DR. MARKUS, SP.AN ( 1C,VIP )
// DR. MUDIB, SP.B / DR. MARKUS, SP.AN / DR. ALFONS, SP.AN / DR
// DR. MUDIB, SP.B / DR. MARKUS, SP.AN / DR. RACHIM, SP.JP / DR
// DR. MUDIB, SP.B / DR. RAHMAD, SP.PD / DR. MARKUS, SP.AN ( PD
// DR. MUSLIM M AMIN SP.THT.KL (PD)
// DR. MUSLIM M. AMIN, SP. THT.KL (ANAK)
// DR. MUSLIM SP.THT.KL (1C)
// DR. MUSLIM SP.THT.KL/DR. ALFONS SP.AN (BEDAH)
// DR. MUSLIM SP.THT.KL/DR. MARKUS SP.AN (1B)
// DR. MUSLIM SP.THT.KL/DR. MARKUS SP.AN (ANAK)
// DR. MUSLIM SP.THT.KL/DR. ZAINUL SP.B/DR. HANARTOAJI SP.S (BE
// DR. MUSLIM, SP.THT / DR. MARKUS, SP.AN ( 1C )
// DR. MUSLIM, SP.THT / DR. MARKUS, SP.AN / DR. DJOKO, SP.M / D
// DR. MUSLIM, SP.THT-KL / DR. ALFONS / DR. MARKUS / DR. DIANA
// DR. MUSLIM, SP.THT-KL / DR. ALFONS, SP.AN ( ANAK )
// DR. MUSLIM, SP.THT-KL / DR. ALFONS, SP.AN ( SYARAF )
// DR. MUSLIM, SP.THT-KL / DR. FREDDY, SP.PD ( BDH )
// DR. MUSLIM, SP.THT-KL / DR. SONNY, SP.BS / DR. ALFONS, SP.AN
// DR. NOVI SALITA SP.OG (NIFAS,VK)
// DR. NOVI SALITA SP.OG/DR. ALFONS SP.AN (NIFAS)
// DR. NOVI SALITA SP.OG/DR. ALFONS SP.AN (VK,NIFAS)
// DR. NOVI SALITA, SP.OG (NFS)
// DR. NOVI SALITA, SP.OG (VK,NFS)
// DR. NOVI SALITA, SP.OG (VK)
// DR. NOVI SALITA, SP.OG / DR. ALFONS, SP.AN ( VK )
// DR. NOVI SP.OG/DR. MARKUS SP.AN (NIFAS)
// DR. NOVI SP.OG/DR. MARKUS SP.AN (VK,NIFAS)
// DR. NOVI, SP.OG / DR. MARKUS, SP.AN ( NFS )
// DR. NOVI, SP.OG / DR. MARKUS, SP.AN ( VK,NFS )
// DR. RACHIM SP.JP/DR. ARI SP.P (1B)
// DR. RACHIM SP.JP/DR. ARI SP.P (PARU)
// DR. RACHIM SP.JP/DR. FREDDY SP.PD (PD)
// DR. RACHIM SP.JP/DR. HANARTOAJI SP.S (VIP)
// DR. RACHIM SP.JP/DR. RAHMAD SP.PD (ICU,VIP)
// DR. RACHIM, SP.JP / DR. ARI, SP.P ( PD )
// DR. RACHIM, SP.JP / DR. ARI, SP.P / DR. FENNY, SP.KJ ( PARU
// DR. RACHIM, SP.JP / DR. ARI, SP.P / DR. MARKUS, SP.AN / DR.
// DR. RACHIM, SP.JP / DR. ARI, SP.P / DR. MUDIB, SP.B / DR. RA
// DR. RACHIM, SP.JP / DR. FENNY, SP.KJ / DR. ALFONS / DR. MARK
// DR. RACHIM, SP.JP / DR. RAHMAD, SP.PD ( 1B )
// DR. RACHIM, SP.JP / DR. RAHMAD, SP.PD ( IGD,PD )
// DR. RACHIM, SP.JP / DR. RAHMAD, SP.PD ( PD )
// DR. RADHITIO ADI, SP.A ( VIP )
// DR. RADHITIO, SP.A ( PERINATOLOGI )
// DR. RADHITIO, SP.A / DR. ALFONS, SP.AN ( IGD,ICU )
// DR. RADHITIO, SP.A / DR. MARKUS, SP.AN ( PERINATOLOGI )
// DR. RAHMAD B SP.PD (PD)
// DR. RAHMAD BUDIANTO SPPD (1C)
// DR. RAHMAD DP.PD/DR. RACHIM SP.JP (PD)
// DR. RAHMAD SP.PD (1B)
// DR. RAHMAD SP.PD (IGD,VIP)
// DR. RAHMAD SP.PD (IGD)
// DR. RAHMAD SP.PD (VIP)
// DR. RAHMAD SP.PD/DR. FENNY SP.KJ (PD)
// DR. RAHMAD SP.PD/DR. HANARTOAJI SP.S (SYARAF)
// DR. RAHMAD SP.PD/DR. M. NUR RACHIM SP.JP (1B)
// DR. RAHMAD SP.PD/DR. MUSLIM SP.THT.KL (1B)
// DR. RAHMAD SP.PD/R. HANARTOAJI SP.S/DR. TOGU SP.KFR (VIP)
// DR. RAHMAD SPPD(VIP)
// DR. RAHMAD, SP.PD ( 1C,SYARAF )
// DR. RAHMAD, SP.PD / DR. ARI, SP.P ( ISO PARU )
// DR. RAHMAD, SP.PD / DR. HANARTOAJI, SP.S / DR. FENNY, SP.KJ
// DR. RAHMAD, SP.PD / DR. HANARTOAJI, SP.S / DR. TOGU, SP.KFR
// DR. RAHMAD, SP.PD / DR. MUDIB, SP.B / DR. MARKUS, SP.AN ( 1C
// DR. RAHMAD, SP.PD / DR. RACHIM, SP.JP ( PD )
// DR. RAHMAD, SP.PD / DR. RACHIM, SP.JP / DR. FENNY, SP.KJ ( P
// DR. SONNY , SPBS ( PD,SYARAF )
// DR. SONNY SP.BS (1B,VIP)
// DR. SONNY SP.BS/DR. AGUSTINUS B SP.OT/DR. DJOKO SP.M/DR. MUS
// DR. SONNY SP.BS/DR. ALFONS SP.AN (SYARAF)
// DR. SONNY SP.BS/DR. ALFONS SP.AN/DR. MARKUS SP.AN (ICU-ICCU)
// DR. SONNY SP.BS/DR. ARI SP.PS/DR. ALFONS SP.AN/DR. MARKUS SP
// DR. SONNY SP.BS/DR. DIANA SP.A (1B,VIP)
// DR. SONNY SP.BS/DR. MARKUS SP.AN (ICU-ICCU,SYARAF)
// DR. SONNY SP.BS/DR. MARKUS SP.AN (SYARAF)
// DR. SONNY SP.BS/DR. MARKUS SP.AN/DR. ALFONS SP.AN (ICU,SYARA
// DR. SONNY SP.BS/DR. MARKUS SP.AN/DR. DIANA SP.A (ICU-ICCU)
// DR. SONNY SP.BS/DR. MARKUS/DR. ALFONS (ICU)
// DR. SONNY SP.BS/DR. RAHMAD SP.PD (SYARAF)
// DR. SONNY SPBS(1B,VIP)
// DR. SONNY SPBS(SARAF)
// DR. SONNY SPBS/DR.RAHMAD SPPD(SARAF)
// DR. SONNY, SP.BS ( SYARAF )
// DR. SONNY, SP.BS / DR. RADHITIO, SP.A / DR. MARKUS, SP.AN (
// DR. SONNY, SP.BS / DR. RAHMAD, SP.PD / DR. ALFONS / DR. MARK
// DR. SONNY, SP.BS / DR. RAHMAD, SP.PD / DR. FENNY, SP.KJ ( 1C
// DR. SONNY, SP.BS / DR. VIVI, SP.N / DR. ALFONS, SP.AN / DR.
// DR. SONNY, SPBS (SYARAF)
// DR. STEVIE SP. A (ANAK)
// DR. STEVIE SP.A/DR. HERISA SP.MK (ANAK)
// DR. STEVIE SP.A/DR. M. NUR RACHIM SP.JP (PERINATOLOGI)
// DR. STEVIE SP.A/DR. MARKUS SP.AN (ANAK)
// DR. STEVIE SP.A/DR. TOGU SP.KFR (ANAK)
// DR. STEVIE SP.A/DR. VIVI SP.N/DR. MARKUS SP.AN (ANAK,VIP)
// DR. STEVIE SP.A/DR. ZAINUL  SP.B (ANAK)
// DR. STEVIE, SP. A (PERINATOLOGI)
// DR. STEVIE, SP. A (VIP)
// DR. STEVIE, SP.A ( ANAK,ICU )
// DR. STEVIE, SP.A ( VK,PERI )
// DR. STEVIE, SP.A / DR. AGUSTINUS, SP.OT / DR. MUDIB, SP.B (
// DR. STEVIE, SP.A / DR. ALFONS, SP.AN ( ANAK,ICU )
// DR. STEVIE, SP.A / DR. VIVI, SP.N / DR. YUNITA, SP.THT ( ANA
// DR. TEGUH, SP.KK / DR. RAHMAD, SP.PD ( PD )
// DR. TEGUH. A, SP. KK (PD)
// DR. URAY YESSIKA SP.B/DR. ALFONS SP.AN (BEDAH)
// DR. URAY YESSIKA SP.B/DR. ALFONS SP.AN/DR. HARTONO SP.PD (BE
// DR. URAY YESSIKA SP.B/DR. MARKUS SP.AN (BEDAH)
// DR. URAY YESSIKA, SP.B ( 1C )
// DR. URAY YESSIKA, SP.B / DR. ALFONS, SP.AN ( ICU,BDH )
// DR. URAY YESSIKA, SP.B / DR. ALFONS, SP.AN / DR. MARKUS, SP.
// DR. URAY YESSIKA, SP.B / DR. MARKUS, SP.AN ( 1C )
// DR. URAY YESSIKA, SP.B / DR. MARKUS, SP.AN ( ICU )
// DR. URAY YESSIKA, SP.B / DR. MARKUS, SP.AN / DR. HARTONO, SP
// DR. URAY YESSIKA, SP.B / DR. MARKUS, SP.AN / DR. RAHMAD, SP.
// DR. VIVI KRISTIANI SP.N (1B)
// DR. VIVI KRISTIANI SP.N (SYARAF)
// DR. VIVI KRISTIANI SP.N/DR. M. NUR RACHIM SP.JP (1B)
// DR. VIVI SP.N/DR. HARTONO SP.PD/DR. ARI SP.P/DR. RACHIM SP.J
// DR. VIVI SP.N/DR. RACHIM SP.JP/DR. ARI SP.P (SYARAF)
// DR. VIVI SP.N/DR. RACHIM SP.JP/DR. MARSITA SP.M/DR. ARI SP.P
// DR. VIVI SP.N/DR. RAHMAD/DR. RACHIM/DR. ARI (SYARAF)
// DR. VIVI, SP.N ( SYARAF )
// DR. VIVI, SP.N / DR. FREDDY, SP.PD / DR. ARI, SP.P ( SYARAF
// DR. VIVI, SP.N / DR. FREDDY, SP.PD / DR. MARSITA, SP.M ( SYA
// DR. VIVI, SP.N / DR. HARTONO, SP.PD ( SYARAF )
// DR. VIVI, SP.N / DR. RAHMAD, SP.PD ( SYARAF )
// DR. VIVI, SP.N / DR. TOGU, SP.KFR ( SYARAF )
// DR. YUNITA SP.THT.KL (ANAK)
// DR. YUNITA SP.THT.KL /DR. ALFONS SP.AN (ANAK)
// DR. YUNITA SP.THT.KL/DR. ALFONS SP.AN (BEDAH)
// DR. YUNITA SP.THT.KL/DR. MARKUS SP.AN (SYARAF)
// DR. YUNITA SP.THT.KL/DR. MARKUS/DR. ALFONS (SYARAF)
// DR. YUNITA SP.THT.KL/DR. RAHMAD SP.PD (BEDAH)
// DR. YUNITA SP.THT.KL/DR. RAHMAD/DR. MARKUS (BEDAH)
// DR. YUNITA SP.THT.KL/DR. SONNY SP.BS/DR. MARKUS SP.AN (SYARA
// DR. YUNITA, SP.THT / DR. MARKUS, SP.AN ( 1C )
// DR. YUNITA, SP.THT.KL / DR. RAHMAD, SP.PD ( PD )
// DR. ZAINNUL SP.B/DR. FREDDY SP.B/DR. ALFONS SP.AN (1C,VIP)
// DR. ZAINUL SP.B (PD,BEDAH)
// DR. ZAINUL SP.B/DR. ALFONS SP.A/DR. FREDDY SP.PD (PD,BEDAH,I
// DR. ZAINUL SP.B/DR. ALFONS SP.AN (1C)
// DR. ZAINUL SP.B/DR. ARI SP.P (BEDAH)
// DR. ZAINUL SP.B/DR. FREDDY SP.PD (BEDAH)
// DR. ZAINUL SP.B/DR. FREDDY SP.PD/DR. ALFONS SP.AN (1C)
// DR. ZAINUL SP.B/DR. HARTONO SP.PD/DR. MARKUS SP.AN (1C)
// DR. ZAINUL SP.B/DR. MARKUS SP.AN/DR. ALFONS SP.AN/DR. DIANA
// DR. ZAINUL SP.B/DR. RACHIM SP.JP/DR. ARI SP.P/DR. BORIS SP.B
// DR. ZAINUL SP.B/DR. RACHIM SP.JP/DR. MARKUS SP.AN/DR. ARI SP
// DR. ZAINUL, SP.B ( 1B )
// DR. ZAINUL, SP.B ( 1C )
// DR. ZAINUL, SP.B (BEDAH)
// DR. ZAINUL, SP.B (PD)
// DR. ZAINUL, SP.B / DR. ALFONS, SP.AN ( 1C,ICU )
// DR. ZAINUL, SP.B / DR. ARI, SP.P / DR. ALFONS, SP.AN / DR. M
// DR. ZAINUL, SP.B / DR. DIANA, SP.A / DR. MARKUS, SP.AN ( PER
// DR. ZAINUL, SP.B / DR. MARKUS, SP.AN ( 1C )
// DR. ZAINUL, SP.B / DR. MARKUS, SP.AN ( VIP )
// DR. ZAINUL, SP.B / DR. MARKUS, SP.AN / DR. FREDDY, SP.PD / D
// DR. ZAINUL, SP.B / DR. RACHIM, SP.JP / DR. MARKUS, SP.AN ( 1
// DR.AGUS BUDHI,SP.OT / DR.ALFONS (BDH)
// DR.AGUS BUDHI,SP.OT/DR.ALFONS,SP.AN (1C)
// DR.AGUS BUDHI,SP.OT/DR.ALFONS(BDH)
// DR.AGUS BUDHI,SP.OT/DR.MARKUS (BEDAH)
// DR.AGUSTINUS B SP.OT/DR. ALFONS SP.AN (1B)
// DR.AGUSTINUS B,SP.OT/DR.ALFONS(BDH)
// DR.AGUSTINUS,SP.OT/DR.HARTONO,SP.PD/DR.ALFONS,SP.AN/DR,MARKU
// DR.AGUSTINUS,SP.OT/DR.MARKUS,SP.AN/DR.FREDDY,SP.PD (BEDAH)
// DR.ARI P,SP.P/DR.M.NUR RACHIM (PARU)
// DR.ARI PRABOWO SP.P ( 1B )
// DR.ARI PRABOWO,SP. P (PARU)
// DR.ARI PRABOWO,SP.P (1B)
// DR.ARI PRABOWO,SP.P (PARU)
// DR.ARI PRABOWO,SP.P (PD)
// DR.ARI PRABOWO,SP.P/DR.RAHMAD (PARU)
// DR.BORIS SP.B/DR. MARKUS SP.AN (BEDAH)
// DR.BORIS,SP.B (1C)
// DR.BORIS,SP.B (BEDAH)
// DR.BORIS,SP.B/DR.ALFONS(BEDAH)
// DR.BORIS,SP.B/DR.ALFONS/DR.HARTONO(BDH)
// DR.BORIS,SPB/DR.ALFONS (BDH)
// DR.DAVIS,SP.OG (VK,NIFAS)
// DR.DAVIS,SP.OG/DR.ALFONS,SP.AN(NFS)
// DR.DAVIS,SP.OG/DR.ALFONS(VK-NF)
// DR.DIANA BANCIN, SP. A (ANAK)
// DR.DIANA BANCIN,SP.A (ANAK)
// DR.DIANA BANCIN,SP.A (VIP)
// DR.DIANA,SP.A (ANAK)
// DR.FREDDY,SP.PD (1B)
// DR.FREDDY,SP.PD(PD)
// DR.FREDDY,SP.PD/DR.BORIS(PD)
// DR.HANARTOAJI,SP.S (IGD)
// DR.HANARTOAJI,SP.S (SYARAF)
// DR.HANARTOAJI,SP.S/DR.RACHIM,SP.JP/DR.TOGU,SP.KFR/DR.RAHMAD,
// DR.HARTONO,SP.PD (PD)
// DR.HARTONO,SP.PD/DR.ARI,SP.P (PD)
// DR.HARTONO,SP.PD/DR.FENNY,SP.KJ (PD)
// DR.M.NUR RACHIM,SP.JP (1B)
// DR.M.NUR RACHIM,SP.JP (PD)
// DR.M.NUR RACHIM,SP.JP/DR.RAHMAD (PD)
// DR.MUDIB SP.B/DR. ALFONS SP.AN (BEDAH)
// DR.MUDIB,SP.B (1C)
// DR.MUDIB,SP.B (BEDAH)
// DR.MUDIB,SP.B/DR.FREDDY(BEDAH)
// DR.MUDIB,SP.B/DR.HARTONO,SP.PD (BEDAH)
// DR.MUDIB,SP.B/DR.HARTONO,SP.PD/DR.ARI,SP.P/DR.ALFONS,SP.AN/D
// DR.MUSLIM SP.THT.KL/DR.MARKUS SP.AN (BEDAH)
// DR.MUSLIM,SP.THT (ANAK)
// DR.MUSLIM,SP.THT/DR.ALFONS(ANAK)
// DR.NOVI SALITA,SP.OG (NFS)
// DR.NOVI SALITA,SP.OG (VK)
// DR.NOVI SALITA,SP.OG(VK-NFS)
// DR.NOVI SALITA,SP.OG/DR.ALFONS(NFS)
// DR.NOVI SALITA,SP.OG/DR.ALFONS(VK-NFS)
// DR.NOVI SP.OG/DR. RAHMAD SP.PD/DR. ALFONS SP.AN (NIFAS)
// DR.RACHIM,SP.JP/DR.FENNY,SP.KJ (PD)
// DR.RAHMAD B,SP.PD (PD)
// DR.RAHMAD,SP.PD (1B)
// DR.RAHMAD,SP.PD/DR.MUDIB,SP.B (PD)
// DR.RAHMAD,SP.PD/DR.TEGUH,SP.KK (1B)
// DR.STEVIE,SP.A (ANAK)
// DR.STEVIE(ANAK)
// DR.VIVI K,SP.N (SYF)
// DR.VIVI,SP.N/DR.HARTONO (SYARAF)
// DR.YUNITA,SP.THT (PD)
// DR.YUNITA,SP.THT/DR.ALFONS,SP.AN (ANAK)
// DR/ STEVIE SP.A/DR. RACHIM SP.JP (PERINATOLOGI)
// RADHITIO, SP.A(PERINATOLOGI)

let js_dpjp = {
    AGUSTINUS: [],
    ALFONS: [],
    "ARI ": [],
    BORIS: [],
    DAVIS: [],
    DIANA: [],
    DJOKO: [],
    ESTU: [],
    FENNY: [],
    FREDDY: [],
    HANARTO: [],
    HARTONO: [],
    HERLING: [],
    HERISA: [],
    MARKUS: [],
    MARSITA: [],
    MUDIB: [],
    MUSLIM: [],
    MARIA: [],
    NOVI: [],
    RAHMAD: [],
    RACHIM: [],
    SONNY: [],
    STEVIE: [],
    TEGUH: [],
    TOGU: [],
    URAY: [],
    UNDARI: [],
    VIVI: [],
    YUNITA: [],
    ZAINUL: []
};
let dpjp_inacbg = "DR. DAVIS SP.OG/DR. ARI SP.P/DR. BORIS SP.B/DR. MARIA ADE SP.M";
// console.log(js_dpjp)
let jumlah_dpjp = 0;
for (let key in js_dpjp) {
    if (dpjp_inacbg.includes('key')) {
    console.log(key);
        jumlah_dpjp++;
}

}
console.log(jumlah_dpjp);