version: '3.8'

services:
  app:
    build: .
    container_name: simrs-webService
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app
      - /opt/lampp/htdocs/webapps/berkasrawat/pages/upload/:/usr/src/app/public/uploads
    environment:
      - .env