version: '3.8'

services:
  app:
    build: .
    container_name: simrs-webService
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - .env

     db.createUser(
        {
           user: "admin",
           pwd: "strong_password_pi", // Replace with a strong password
           roles: [
              { role: "userAdminAnyDatabase", db: "admin" },
              { role: "dbAdminAnyDatabase", db: "admin" },
              { role: "readWriteAnyDatabase", db: "admin" },
              { role: "clusterAdmin", db: "admin" } // Optional, for cluster administration
           ]
        }
     )